# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# see https://docs.zephyrproject.org/latest/kconfig.html
# for config descriptions

CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SMF=y
