# provide debug symbols
CONFIG_DEBUG=y
CONFIG_ASSERT=y
CONFIG_THREAD_NAME=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_EXTERNAL_LIBC=y

# sanitizers
CONFIG_ASAN=y
CONFIG_UBSAN=y

# driver emulators
CONFIG_GPIO_EMUL=y

# logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_NATIVE_POSIX=y
